### PR TITLE
Update list of css properties needing prefixing

### PR DESCRIPTION
**Pull request by dontcallmedom**
ref https://github.com/w3c/Mobile-Checker/issues/47#issuecomment-114635340

### CODE REVIEW

**Comment by guibbs** [comment]
Guess we will need to update our tests before merging that

**Comment by guibbs** [comment]
seems like jsdom < 4.x is not compatible. why did we need to downgrade jsdom?

**Comment by dontcallmedom** [comment]
jsdom refuses to run with node.js (only io.js) in versions >= 4.x

**Comment by guibbs** [comment]
well, that's interesting. jsdom refuses for all node version? even 0.12 ?

**Comment by dontcallmedom** [comment]
https://github.com/tmpvar/jsdom says
> Note that as of our 4.0.0 release, jsdom no longer works with Node.js™, and instead requires io.js. 
> You are still welcome to install a release in the 3.x series if you use Node.js™.

**Comment by dontcallmedom** [comment]
any reason not to merge this?

**Comment by guibbs** [comment]
the Travis build failed no?

**Comment by dontcallmedom** [comment]
But not due to this change specifically as far as I can tell. Our Travis CI set up seems in a bad shape, but I wouldn't put that in front of a (fairly simple) bug fix.

**Comment by guibbs** [comment]
makes sens :)

**Pull request merged**
