### PR TITLE
[Stalled] Update npm dependencies

### PR DESCRIPTION
**Pull request by tripu**
&hellip;running [updtr](https://github.com/peerigon/updtr).

While at it:
- Fix order of dependencies (alphabetically).
- Enable [growl notifications](https://mochajs.org/#mocha-opts) in mocha, and turn on coloured output explicitly.

### CODE REVIEW

**Comment by tripu** [comment]
[This build](https://travis-ci.org/w3c/Mobile-Checker/builds/94198698):

    $ wget https://s3-us-west-1.amazonaws.com/lightbody-bmp/browsermob-proxy-2.0-beta-9-bin.zip
    HTTP request sent, awaiting response... 403 Forbidden
    2015-12-02 05:23:21 ERROR 403: Forbidden.
    The command "wget https://s3-us-west-1.amazonaws.com/lightbody-bmp/browsermob-proxy-2.0-beta-9-bin.zip" failed and exited with 8 during .

While [the last successful `master`](https://travis-ci.org/w3c/Mobile-Checker/builds/69915817):

    $ wget https://s3-us-west-1.amazonaws.com/lightbody-bmp/browsermob-proxy-2.0-beta-9-bin.zip
    HTTP request sent, awaiting response... 200 OK

I restarted the build, but same result.

What am I missing?

**Comment by tripu** [comment]
@dontcallmedom, @guibbs: builds are failing, but it's not because of the changes in this PR ([`master` fails right now too](https://travis-ci.org/w3c/Mobile-Checker/builds/70390047)).

Can we merge this while we find out what's wrong with Travis&hellip;?

**Comment by dontcallmedom** [comment]
unless there is a particular emergency in merging this, I would rather wait until we ensure the changes are not breaking this any further.

**Comment by tripu** [comment]
OK, @dontcallmedom. Leaving it open for a while at least, then.

**Comment by tripu** [comment]
Updated all packages again.
I know some of these automatic updates may break the build, but since the build is broken anyway, it's difficult to tell.
Perhaps we can use this PR as a starting point to sanitise dependencies and get a working build again?

**Comment by guibbs** [comment]
@tripu , did you try to run the Mobile Checker with those changes? It broken on my side after I merged this branch locally. Im looking into it but if you have an idea tell me :)

**Comment by tripu** [comment]
@guibbs, `master` can't build as it is now ([see Travis](https://travis-ci.org/w3c/Mobile-Checker/builds/70390047)) because `https://s3-us-west-1.amazonaws.com/lightbody-bmp/browsermob-proxy-2.0-beta-9-bin.zip` [doesn't exist](https://github.com/w3c/Mobile-Checker/blob/master/.travis.yml#L3).

**Comment by guibbs** [comment]
@tripu yes, but I can't get the Mobile Checker running even locally on my laptop. 

```
Users/guillaume/Documents/W3C/Mobile-Checker/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/guillaume/Documents/W3C/Mobile-Checker/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/guillaume/Documents/W3C/Mobile-Checker/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:541:32)
```

**Comment by guibbs** [comment]
``` node app.js ``` if I apply those changes

**Comment by tripu** [comment]
@guibbs, if I apply to current `master` my changes in `.travis.yml` *only* , I don't see that error, but a different bunch of errors. The test suite gives me 16 errors (I'm investigating some of them) and execution gives me a few others that crash the server.

(Anyway, these errors are not about my npm upates here; they're related to upgrading BrowserMob Proxy from `2.0-beta-9` to `2.1.1`. Either you do that, or you find a download location for `2.0-beta-9`&hellip;)

**Comment by qwertychouskie** [comment]
2.0 release bin is here: https://github.com/lightbody/browsermob-proxy/releases/download/browsermob-proxy-2.0.0/browsermob-proxy-2.0.0-bin.zip
This should be similar enough.

**Review by shenky9996 — COMMENTED** [review]
Great.

**Pull request closed without merging**
