### PR TITLE
Fix travis build?

### PR DESCRIPTION
**Pull request by qwertychouskie**
(Hopefully.)

### CODE REVIEW

**Comment by qwertychouskie** [comment]
Well, it didn't die immediately, but still failed.  A step in the right direction?

**Comment by qwertychouskie** [comment]
`https://googledrive.com/host/0B5VlNZ_Rvdw6NTJoZDBSVy1ZdkE` no longer exists.  Does anyone have the proper link?

**Comment by qwertychouskie** [comment]
Well, it gets a lot farther than before, but an updated link for that file is still needed.  Starting with https://travis-ci.org/w3c/Mobile-Checker/builds/226513425#L1902, all the errors seem to be caused by that missing file.

**Comment by tripu** [comment]
Thank you for your efforts, @qwertychouskie.

As you may have noticed, [maintenance of the Mobile Checker by W3C is on hold for the moment](https://www.w3.org/2016/11/mobile-checker-disabled/).

That being said, I think any progress you made towards having it working again would be of value. Talk to @dontcallmedom for details.

**Comment by qwertychouskie** [comment]
I saw that, my hope is that if the builds can be fixed, then it will serve as a starting point for getting the dependencies up-to-date and secure, so maybe the service can eventually be re-enabled ([the old MobileOK checker](http://mobile.css-validator.org/) gives a "Severity: critical" error if the page in total is more than 20KB, talk about outdated. :).

**Comment by qwertychouskie** [comment]
OK, it seems Travis is now giving genuine errors, rather than errors related to the configuration.  Can you and/or @dontcallmedom take a look at https://travis-ci.org/w3c/Mobile-Checker/builds/227032053 and see if you guys know how to fix the errors?  I'll also experiment with the dependencies to see if I can figure anything out.

**Comment by dontcallmedom** [comment]
@qwertychouskie thank you so much for getting this started! I'll try to look into the failing tests this week (now that the build runs) - this is extremelly helpful.

**Comment by qwertychouskie** [comment]
@dontcallmedom Thanks! Can you also take a look at https://github.com/w3c/mobile-web-browser-emulator/issues/15?  The build there works, so it should be just a matter of making sure I didn't do anything wrong, then merging and uploading to npm.

**Comment by HizkiFW** [comment]
The Google Drive link can be replaced with https://drive.google.com/uc?id=0B5VlNZ_Rvdw6NTJoZDBSVy1ZdkE btw

**Comment by qwertychouskie** [comment]
@HizkiFW Thanks, but I actually found another way around it (specifically, telling Travis to use Trusty instead of Precise).  Currently waiting for https://www.npmjs.com/package/mobile-web-browser-emulator to be updated by @dontcallmedom / @tripu (see https://github.com/w3c/mobile-web-browser-emulator/issues/17).

**Comment by tripu** [comment]
@qwertychouskie, current version published to npm!

**Comment by tripu** [comment]
@qwertychouskie, could you make any progress with this&hellip;?

**Comment by qwertychouskie** [comment]
@tripu At this point, 34 tests are passing and 10 are failing.  At this point, I don't know how to fix the remaining issues, so probably merge this now and if I figure out anything else I'll open a new PR.

**Review by tripu — APPROVED** [review]
Better than what's in `master` now, it seems.
@dontcallmedom, wdyt?

**Comment by tripu** [comment]
@dontcallmedom?

**Comment by qwertychouskie** [comment]
Thanks!

**Pull request merged**
