### PR TITLE
Dependencies²

### PR DESCRIPTION
**Pull request by astorije**
**WIP**

5352eaa removes this inelegant `insecure` badge, but careful, I wouldn't be surprised if this commit had broken something so please try locally before merging: `git fetch && git checkout astorije/deps && npm start` is already a start, but actually playing with the checker a little bit would give you better guarantees.

I could not update `compression` in the `devDependencies` (from `1.0.11` to `^1.4.4`) without making Travis CI weep :-(.

### CODE REVIEW

**Comment by astorije** [comment]
@guibbs, closing this as I believe it won't go anywhere. Feel free to re-open if I am wrong.

**Comment by tripu** [comment]
I agree with @astorije: what's the point of those badges, Travis, David and Coveralls if we don't care to look at their output?

See #132 and #133.

**Comment by astorije** [comment]
Well you tell me, I'm not in charge of the project, and I did open that PR mindful of the badges 3/4 of a year ago :-P

**Comment by astorije** [comment]
You can reopen the PR if you feel it's still relevant, and I believe I have a bunch of them open out there if you want to follow-up.

**Comment by tripu** [comment]
> Well you tell me, I'm not in charge of the project, and I did open that PR mindful of the badges 3/4 of a year ago :-P

Hey, man&hellip; I was siding with you here :)

**Comment by guibbs** [comment]
Sorry guys. Gonna test that tonight or tomorrow.

**Comment by tripu** [comment]
@astorije, @dontcallmedom: `npm install` throws errors for me (Node `8.3.0`, npm `5.3.0`)&nbsp;&mdash;&nbsp;both in `master` and in this branch here. Can you reproduce it?

Culprits seem to be build scripts of [package `contextify`](https://www.npmjs.com/package/contextify), which is old and not needed. But I don't even know the chain of dependencies leading to that package.

Any idea? Is it even worth fixing, given this project is stalled? [No Travis builds have succeeded for more than two years now](https://travis-ci.org/w3c/Mobile-Checker/builds).

```
> contextify@0.1.15 install node_modules/contextify
> node-gyp rebuild

make: Entering directory 'node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function ‘static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)’:
../src/contextify.cc:131:68: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
In file included from ~/.node-gyp/8.3.0/include/node/v8.h:26:0,
                 from ~/.node-gyp/8.3.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
~/.node-gyp/8.3.0/include/node/v8.h:3792:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
~/.node-gyp/8.3.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/contextify.cc:150:16: error: ‘class v8::ObjectTemplate’ has no member named ‘SetAccessCheckCallbacks’; did you mean ‘SetAccessCheckCallback’?
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
                ^~~~~~~~~~~~~~~~~~~~~~~
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)’:
../src/contextify.cc:182:80: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                                ^
In file included from ~/.node-gyp/8.3.0/include/node/v8.h:26:0,
                 from ~/.node-gyp/8.3.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
~/.node-gyp/8.3.0/include/node/v8.h:3345:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
~/.node-gyp/8.3.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)’:
../src/contextify.cc:209:67: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
In file included from ~/.node-gyp/8.3.0/include/node/v8.h:26:0,
                 from ~/.node-gyp/8.3.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
~/.node-gyp/8.3.0/include/node/v8.h:3345:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
~/.node-gyp/8.3.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/contextify.cc:210:71: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                       ^
In file included from ~/.node-gyp/8.3.0/include/node/v8.h:26:0,
                 from ~/.node-gyp/8.3.0/include/node/node.h:63,
                 from ../src/contextify.cc:1:
~/.node-gyp/8.3.0/include/node/v8.h:3345:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
~/.node-gyp/8.3.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
contextify.target.mk:95: recipe for target 'Release/obj.target/contextify/src/contextify.o' failed
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory 'node_modules/contextify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.10.0-32-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd node_modules/contextify
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2017-08-14T09_08_46_871Z-debug.log
```

**Comment by astorije** [comment]
@tripu, [I get a bunch of deprecation warnings, but apart from that it installs fine](https://zerobin.net/?7c5deb233cd4d20d#K8e85yP2Sch7Xwi1csvXQEmVvkFUO8EmCywJpaLuJQI=).

```
$ node -v
v6.9.4
$ npm -v
3.10.10
```

It seems to me that you have issues with your `node-gyp` and might need to rebuild or something.

That being said, feel free to close this PR / delete this branch as 1) I will not be able to commit to further work, 2) most dependencies upgraded by this PR have probably seen newer versions anyway (even PR conflicts actually).

👋😃

**Comment by tripu** [comment]
> It seems to me that you have issues with your node-gyp and might need to rebuild or something.

That's strange. I build from a clean clone, with no `node_modules/` dir or anything; and I have just 4 npm packages installed globally, none of them related to that &ldquo;gyp&rdquo; (afaict). Anyway, you and I are using different versions of Node.js and npm.

@dontcallmedom, can you build `master`?

btw, Travis builds use Node.js 0.10.x &mdash; we should update that.

I'm closing this, as suggested by @astorije &mdash; for lack of ideas, urgency and manpower.

But thank you, @astorije!

**Pull request closed without merging**
